export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAILED";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_SIGNING = "USER_SIGNING";


// fetch many entity of projects
export const STARRED_REQUEST_PROJECTS = "STARRED_REQUEST_PROJECTS";
export const STARRED_SUCCESS_PROJECTS = "STARRED_SUCCESS_PROJECTS";
export const STARRED_FAILURE_PROJECTS = "STARRED_FAILURE_PROJECTS";
// action for update or create or delete one entity
export const START_UPDATE_PROJECT = "START_UPDATE_PROJECT";
export const UPDATE_SUCCESS_PROJECT = "UPDATE_SUCCESS_PROJECT";
export const REMOVE_SUCCESS_PROJECT = "REMOVE_SUCCESS_PROJECT";
export const UPDATE_FAILURE_PROJECT = "UPDATE_FAILURE_PROJECT";
// fetch one entity
export const FETCH_SUCCESS_PROJECT = "FETCH_SUCCESS_PROJECT";
export const STARRED_FETCH_PROJECT = "STARRED_FETCH_PROJECT";
export const FETCH_FAILURE_PROJECT = "FETCH_FAILURE_PROJECT";
// clear cache project
export const CLEAR_CACHE_PROJECT = "CLEAR_CACHE_PROJECT";


// fetch many entity of sprints
export const STARRED_REQUEST_SPRINTS = "STARRED_REQUEST_SPRINTS";
export const STARRED_SUCCESS_SPRINTS = "STARRED_SUCCESS_SPRINTS";
export const STARRED_FAILURE_SPRINTS = "STARRED_FAILURE_SPRINTS";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_SPRINT = "UPDATE_SUCCESS_SPRINT";
export const REMOVE_SUCCESS_SPRINT = "REMOVE_SUCCESS_SPRINT";
export const START_UPDATE_SPRINT = "START_UPDATE_SPRINT";
export const UPDATE_FAILURE_SPRINT = "UPDATE_FAILURE_SPRINT";
// fetch one sprint
export const FETCH_SUCCESS_SPRINT = "FETCH_SUCCESS_SPRINT";
export const STARRED_FETCH_SPRINT = "STARRED_FETCH_SPRINT";
export const FETCH_FAILURE_SPRINT = "FETCH_FAILURE_SPRINT";
// clear cache sprint
export const CLEAR_CACHE_SPRINT = "CLEAR_CACHE_SPRINT";


// fetch many entity of tasks
export const STARRED_REQUEST_TASKS = "STARRED_REQUEST_TASKS";
export const STARRED_SUCCESS_TASKS = "STARRED_SUCCESS_TASKS";
export const STARRED_FAILURE_TASKS = "STARRED_FAILURE_TASKS";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_TASK = "UPDATE_SUCCESS_TASK";
export const REMOVE_SUCCESS_TASK = "REMOVE_SUCCESS_TASK";
export const START_UPDATE_TASK = "START_UPDATE_TASK";
export const UPDATE_FAILURE_TASK = "UPDATE_FAILURE_TASK";
// fetch one entity
export const FETCH_SUCCESS_TASK = "FETCH_SUCCESS_TASK";
export const STARRED_FETCH_TASK = "STARRED_FETCH_TASK";
export const FETCH_FAILURE_TASK = "FETCH_FAILURE_TASK";
// clear cache task
export const CLEAR_CACHE_TASK = "CLEAR_CACHE_TASK";

// fetch many entity of users
export const STARRED_REQUEST_USERS = "STARRED_REQUEST_USERS";
export const STARRED_SUCCESS_USERS = "STARRED_SUCCESS_USERS";
export const STARRED_FAILURE_USERS = "STARRED_FAILURE_USERS";
// fetch one entity
export const FETCH_SUCCESS_USER = "FETCH_SUCCESS_USER";
export const STARRED_FETCH_USER = "STARRED_FETCH_USER";
export const FETCH_FAILURE_USER = "FETCH_FAILURE_USER";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_USER = "UPDATE_SUCCESS_USER";
export const REMOVE_SUCCESS_USER = "REMOVE_SUCCESS_USER";
export const START_UPDATE_USER = "START_UPDATE_USER";
export const UPDATE_FAILURE_USER = "UPDATE_FAILURE_USER";
// clear cache user
export const CLEAR_CACHE_USER = "CLEAR_CACHE_USER";


// fetch many entity of problems
export const STARRED_REQUEST_PROBLEMS = "STARRED_REQUEST_PROBLEMS";
export const STARRED_SUCCESS_PROBLEMS = "STARRED_SUCCESS_PROBLEMS";
export const STARRED_FAILURE_PROBLEMS = "STARRED_FAILURE_PROBLEMS";
// fetch one entity
export const FETCH_SUCCESS_PROBLEM = "FETCH_SUCCESS_PROBLEM";
export const STARRED_FETCH_PROBLEM = "STARRED_FETCH_PROBLEM";
export const FETCH_FAILURE_PROBLEM = "FETCH_FAILURE_PROBLEM";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_PROBLEM = "UPDATE_SUCCESS_PROBLEM";
export const REMOVE_SUCCESS_PROBLEM = "REMOVE_SUCCESS_PROBLEM";
export const START_UPDATE_PROBLEM = "START_UPDATE_PROBLEM";
export const UPDATE_FAILURE_PROBLEM = "UPDATE_FAILURE_PROBLEM";
// clear cache problems
export const CLEAR_CACHE_PROBLEM = "CLEAR_CACHE_PROBLEM";


// fetch many entity of documents
export const STARRED_REQUEST_DOCUMENTS = "STARRED_REQUEST_DOCUMENTS";
export const STARRED_SUCCESS_DOCUMENTS = "STARRED_SUCCESS_DOCUMENTS";
export const STARRED_FAILURE_DOCUMENTS = "STARRED_FAILURE_DOCUMENTS";
// fetch one entity
export const FETCH_SUCCESS_DOCUMENT = "FETCH_SUCCESS_DOCUMENT";
export const STARRED_FETCH_DOCUMENT = "STARRED_FETCH_DOCUMENT";
export const FETCH_FAILURE_DOCUMENT = "FETCH_FAILURE_DOCUMENT";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_DOCUMENT = "UPDATE_SUCCESS_DOCUMENT";
export const REMOVE_SUCCESS_DOCUMENT = "REMOVE_SUCCESS_DOCUMENT";
export const START_UPDATE_DOCUMENT = "START_UPDATE_DOCUMENT";
export const UPDATE_FAILURE_DOCUMENT = "UPDATE_FAILURE_DOCUMENT";
// clear cache document
export const CLEAR_CACHE_DOCUMENT = "CLEAR_CACHE_DOCUMENT";

// fetch many entity of discussion
export const STARRED_REQUEST_DISCUSSIONS = "STARRED_REQUEST_DISCUSSIONS";
export const STARRED_SUCCESS_DISCUSSIONS = "STARRED_SUCCESS_DISCUSSIONS";
export const STARRED_FAILURE_DISCUSSIONS = "STARRED_FAILURE_DISCUSSIONS";
// fetch one entity
export const FETCH_SUCCESS_DISCUSSION = "FETCH_SUCCESS_DISCUSSION";
export const STARRED_FETCH_DISCUSSION = "STARRED_FETCH_DISCUSSION";
export const FETCH_FAILURE_DISCUSSION = "FETCH_FAILURE_DISCUSSION";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_DISCUSSION = "UPDATE_SUCCESS_DISCUSSION";
export const REMOVE_SUCCESS_DISCUSSION = "REMOVE_SUCCESS_DISCUSSION";
export const START_UPDATE_DISCUSSION = "START_UPDATE_DISCUSSION";
export const UPDATE_FAILURE_DISCUSSION = "UPDATE_FAILURE_DISCUSSION";
// clear cache discussion
export const CLEAR_CACHE_DISCUSSION = "CLEAR_CACHE_DISCUSSION";


// fetch many entity of comments
export const STARRED_REQUEST_COMMENTS = "STARRED_REQUEST_COMMENTS";
export const STARRED_SUCCESS_COMMENTS = "STARRED_SUCCESS_COMMENTS";
export const STARRED_FAILURE_COMMENTS = "STARRED_FAILURE_COMMENTS";
// fetch one entity
export const FETCH_SUCCESS_COMMENT = "FETCH_SUCCESS_COMMENT";
export const STARRED_FETCH_COMMENT = "STARRED_FETCH_COMMENT";
export const FETCH_FAILURE_COMMENT = "FETCH_FAILURE_COMMENT";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_COMMENT = "UPDATE_SUCCESS_COMMENT";
export const REMOVE_SUCCESS_COMMENT = "REMOVE_SUCCESS_COMMENT";
export const START_UPDATE_COMMENT = "START_UPDATE_COMMENT";
export const UPDATE_FAILURE_COMMENT = "UPDATE_FAILURE_COMMENT";
// clear cache comment
export const CLEAR_CACHE_COMMENT = "CLEAR_CACHE_COMMENT";


// fetch many entity of  topDiscussion
export const STARRED_REQUEST_TOP_DISCUSSIONS = "STARRED_REQUEST_TOP_DISCUSSIONS";
export const STARRED_SUCCESS_TOP_DISCUSSIONS = "STARRED_SUCCESS_TOP_DISCUSSIONS";
export const STARRED_FAILURE_TOP_DISCUSSIONS = "STARRED_FAILURE_TOP_DISCUSSIONS";
// clear cache top discussion
export const CLEAR_CACHE_TOP_DISCUSSION = "CLEAR_CACHE_TOP_DISCUSSION";

// fetch many entity of  topDiscussion
export const STARRED_REQUEST_LATEST_DISCUSSIONS = "STARRED_REQUEST_LATEST_DISCUSSIONS";
export const STARRED_SUCCESS_LATEST_DISCUSSIONS = "STARRED_SUCCESS_LATEST_DISCUSSIONS";
export const STARRED_FAILURE_LATEST_DISCUSSIONS = "STARRED_FAILURE_LATEST_DISCUSSIONS";
// clear cache top discussion
export const CLEAR_CACHE_LATEST_DISCUSSION = "CLEAR_CACHE_LATEST_DISCUSSION";


// fetch many entity of weekSprints
export const STARRED_REQUEST_WEEK_SPRINTS = "STARRED_REQUEST_WEEK_SPRINTS";
export const STARRED_SUCCESS_WEEK_SPRINTS = "STARRED_SUCCESS_WEEK_SPRINTS";
export const STARRED_FAILURE_WEEK_SPRINTS = "STARRED_FAILURE_WEEK_SPRINTS";
// clear cache weekSprints
export const CLEAR_CACHE_WEEK_SPRINT = "CLEAR_CACHE_WEEK_SPRINT";


// fetch many entity of weekTasks
export const STARRED_REQUEST_WEEK_TASKS = "STARRED_REQUEST_WEEK_TASKS";
export const STARRED_SUCCESS_WEEK_TASKS = "STARRED_SUCCESS_WEEK_TASKS";
export const STARRED_FAILURE_WEEK_TASKS = "STARRED_FAILURE_WEEK_TASKS";
// clear cache weekTasks
export const CLEAR_CACHE_WEEK_TASK = "CLEAR_CACHE_WEEK_TASK";

// fetch many entity of latest projects
export const STARRED_REQUEST_LATEST_PROJECTS = "STARRED_REQUEST_LATEST_PROJECTS";
export const STARRED_SUCCESS_LATEST_PROJECTS = "STARRED_SUCCESS_LATEST_PROJECTS";
export const STARRED_FAILURE_LATEST_PROJECTS = "STARRED_FAILURE_LATEST_PROJECTS";
// clear cache latest projects
export const CLEAR_CACHE_LATEST_PROJECT = "CLEAR_CACHE_LATEST_PROJECT";

// fetch many entity of notes
export const STARRED_REQUEST_NOTES = "STARRED_REQUEST_NOTES";
export const STARRED_SUCCESS_NOTES = "STARRED_SUCCESS_NOTES";
export const STARRED_FAILURE_NOTES = "STARRED_FAILURE_NOTES";
// action for update or create or delete one entity
export const UPDATE_SUCCESS_NOTE = "UPDATE_SUCCESS_NOTE";
export const REMOVE_SUCCESS_NOTE = "REMOVE_SUCCESS_NOTE";
export const START_UPDATE_NOTE = "START_UPDATE_NOTE";
export const UPDATE_FAILURE_NOTE = "UPDATE_FAILURE_NOTE";
// fetch one entity
export const FETCH_SUCCESS_NOTE = "FETCH_SUCCESS_NOTE";
export const STARRED_FETCH_NOTE = "STARRED_FETCH_NOTE";
export const FETCH_FAILURE_NOTE = "FETCH_FAILURE_NOTE";
// clear cache note
export const CLEAR_CACHE_NOTE = "CLEAR_CACHE_NOTE";


// fetch many entity of project tasks
export const STARRED_REQUEST_PROJECT_TASKS = "STARRED_REQUEST_PROJECT_TASKS";
export const STARRED_SUCCESS_PROJECT_TASKS = "STARRED_SUCCESS_PROJECT_TASKS";
export const STARRED_FAILURE_PROJECT_TASKS = "STARRED_FAILURE_PROJECT_TASKS";
// clear cache project tasks
export const CLEAR_CACHE_PROJECT_TASKS = "CLEAR_CACHE_PROJECT_TASKS";


/**
 * Appends REQUEST async action type
 */

export const REQUEST = actionType => `${actionType}_PENDING`;

/**
 * Appends SUCCESS async action type
 */

export const SUCCESS = actionType => `${actionType}_FULFILLED`;

/**
 * Appends FAILURE async action type
 */

export const FAILURE = actionType => `${actionType}_REJECTED`;
